### PR TITLE
added git so we can refer to git in packages.json

### PR DESCRIPTION
**Pull request by allandegnan**
There may be some debate on whether on not we should have git in the base image but since we have some private git based modules we install I'm putting in the PR so we can decide.

We might also want to add make.

### CODE REVIEW

**Comment by vaijab** [comment]
Makes sense to have git. LGTM

**Comment by jon-shanks** [comment]
I guess once we have artifactory and our packages are inside our own npm repos, this shouldn't really be needed? This is a question as not sure if it would or not, i'm guessing not as we should be publishing things there? If not then we should maybe some how earmark the PR to come back to once we have it in place.

**Comment by allandegnan** [comment]
That would be a question more for @PurpleBooth or @chrisns but at the moment we have a private module in git that we need to download.  If there's a proper way to make that problem go away without installing git, I'm happy to fix it (assuming it's not waiting for an undetermined amount of time for licensed software).  

Alternatively, I have my own Dockerfile for this currently that I can continue to use.

**Comment by jon-shanks** [comment]
Yep, this is fine, LGTM but just more we need to remove this as being a necessary thing, (artifactory is coming) we have the license btw.

**Pull request merged**
